language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_install:
  - npm update
after_success:
  - bash <(curl -s https://codecov.io/bash)
  script:
- npm test
- codecov
