language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
cache:
  directories:
    - "node_modules"
before_install:
  - npm update
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 7a4ed0f7-6fce-404d-ae1c-b83fa38ba372
  script:
- npm test
- codecov
