language: node_js
node_js:
  - "stable"
branches:
only:
  - master
cache:
directories:
  - "node_modules"
services:
  - postgresql
before_install:
  - npm update
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER bobby WITH PASSWORD 'qwerty';" -U postgres
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - npm run coverage
  - codecov
