language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
cache:
  directories:
    - "node_modules"
before_install:
  - npm update
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
